# Project-wide Gradle settings.

# JVM/daemon settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true

# Packaging
android.enablePngCrunchInReleaseBuilds=true
android.enableMinifyInReleaseBuilds=true
android.enableShrinkResourcesInReleaseBuilds=true

# Architectures / New Arch / Hermes
reactNativeArchitectures=armeabi-v7a,arm64-v8a
newArchEnabled=true
hermesEnabled=true

# Expo image formats
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Dev tools
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Native libs packaging
expo.useLegacyPackaging=false

# Signing (release)
MYAPP_UPLOAD_STORE_FILE=release-key.jks
MYAPP_UPLOAD_KEY_ALIAS=mview
MYAPP_UPLOAD_STORE_PASSWORD=moroccoview2025
MYAPP_UPLOAD_KEY_PASSWORD=moroccoview2025

# Kotlin
kotlin.code.style=official
kotlin.version=1.9.23
ksp.version=1.0.17

# UI edge-to-edge flag consumed by config
expo.edgeToEdgeEnabled=false


